const wikiData = {
    "Dining Directory": {
        description: "The big list. Sortable and filterable. Click Name for Menu.",
        type: "table",
        items: [
            { name: "Selena's at Willow Lake Tavern", location: "East End", cuisine: "American (Upscale & Contemporary)", dish: "Creole Cuisine & Outdoor Patio", url: "https://selenasrestaurant.com", price: "$$" },
            { name: "koko + rae", location: "Highlands", cuisine: "Mexican Latin & Caribbean", dish: "Jerk Chicken Bowl & Oxtail", url: "", price: "$$" },
            { name: "Lee's Korean Restaurant", location: "Poplar Level", cuisine: "Asian", dish: "Bulgogi & Galbi", url: "https://www.facebook.com/LeesKorean/", price: "$$" },
            { name: "Bon Air Tavern", location: "Buechel / Hikes Point", cuisine: "Pub & Bar", dish: "The Kozy Burger", url: "https://www.facebook.com/BonAirTavern/", price: "$" },
            { name: "Kingsley Meats", location: "Taylorsville Rd", cuisine: "American (Casual & Burgers)", dish: "Crab Cakes & Deli Sandwiches", url: "https://kingsleymeats.com/deli-menu/", price: "$" },
            { name: "Bearno's Pizza", location: "Taylorsville Rd", cuisine: "Pizza", dish: "Mama Bearno's Pizza", url: "https://bearnos.com", price: "$$" },
            { name: "Le Relais", location: "Taylorsville Rd", cuisine: "International & Mediterranean", dish: "French Classics & Airport View", url: "https://lerelaisrestaurant.com/dinner/", price: "$$$" },
            { name: "Shady Lane Cafe", location: "East End", cuisine: "American (Casual & Burgers)", dish: "Chicken Salad", url: "https://shadylanecafelouisville.com", price: "$" },
            { name: "Mesh", location: "East End", cuisine: "American (Upscale & Contemporary)", dish: "Steak Frites & Patio Dining", url: "https://meshrestaurants.com/louisville", price: "$$" },
            { name: "Pat's Steakhouse", location: "East End", cuisine: "Steakhouse", dish: "Old School Steaks & Lima Beans", url: "https://patssteakhouselouisville.com", price: "$$$" },
            { name: "Anoosh Bistro", location: "East End", cuisine: "American (Upscale & Contemporary)", dish: "Salmon & Vegetarian Options", url: "https://anooshbistro.com", price: "$$$" },
            { name: "Jasmin Bakery European Bread", location: "Buechel / Hikes Point", cuisine: "International & Mediterranean", dish: "Gyros & Fresh Bread", url: "https://www.facebook.com/JasminBakeryLouisville", price: "$" },
            { name: "Las Gorditas", location: "Buechel / Hikes Point", cuisine: "Mexican Latin & Caribbean", dish: "Authentic Gorditas & Tacos", url: "https://www.facebook.com/LasGorditasLouisville", price: "$" },
            { name: "Aljazzar Meats & Grill", location: "Buechel / Hikes Point", cuisine: "International & Mediterranean", dish: "Shawarma & Mixed Grill", url: "https://aljazzarmeatsandgrill.com", price: "$" },
            { name: "Eden and Kissi", location: "Buechel / Hikes Point", cuisine: "International & Mediterranean", dish: "Afro-Caribbean Chicken & Wings", url: "https://edenandkissi.com", price: "$$" },
            { name: "Momo House", location: "Buechel / Hikes Point", cuisine: "Asian", dish: "Momos & Nepali Thali", url: "https://momohouseandbar.com", price: "$$" },
            { name: "Bellissimo", location: "Buechel / Hikes Point", cuisine: "International & Mediterranean", dish: "Afghan & Italian Fusion (Qabili Palow)", url: "https://www.facebook.com/bellissimo.lou", price: "$$" },
            { name: "Butchertown Bakery", location: "Butchertown", cuisine: "Bakery & Breakfast", dish: "Croissants & Morning Bun", url: "https://butchertownbakery.com/", price: "$" },
            { name: "Vernon Lanes", location: "Butchertown", cuisine: "Pub & Bar", dish: "Bowling Alley Burger & Beer Cheese", url: "https://vernonlanes.com", price: "$$" },
            { name: "Pizza Lupo", location: "Butchertown", cuisine: "Pizza", dish: "Neapolitan Pizza & Sting Like a Bee", url: "https://pizzalupo.com", price: "$$" },
            { name: "Cultured", location: "Butchertown", cuisine: "American (Casual & Burgers)", dish: "Cheese & Charcuterie", url: "https://culturedcheese.com/", price: "$$" },
            { name: "Decade", location: "Butchertown", cuisine: "American (Upscale & Contemporary)", dish: "New American & Cocktails", url: "https://decaderestaurant.com", price: "$$" },
            { name: "Yachtsea", location: "Butchertown", cuisine: "Seafood", dish: "Hot Dogs & Oysters", url: "https://www.instagram.com/yachtsea_ky", price: "$$" },
            { name: "Wagner's Pharmacy", location: "South Louisville", cuisine: "American (Casual & Burgers)", dish: "Diner Breakfast & Derby Pie", url: "https://wagnerspharmacy.com", price: "$" },
            { name: "Caffe Classico", location: "Clifton", cuisine: "International & Mediterranean", dish: "Gelato & Paninis", url: "https://caffeclassico.com", price: "$" },
            { name: "SmashD", location: "Clifton", cuisine: "American (Casual & Burgers)", dish: "Double SmashD Burger", url: "https://smashdburgersandfries.com", price: "$" },
            { name: "The Irish Rover", location: "Clifton", cuisine: "Pub & Bar", dish: "Scotch Eggs & Fish and Chips", url: "https://thelirishroverky.com", price: "$$" },
            { name: "Ciao Ristorante", location: "Clifton", cuisine: "Italian", dish: "Pasta & Italian Classics", url: "https://ciaolouisville.com", price: "$$" },
            { name: "The Manhattan Project", location: "Clifton", cuisine: "Pub & Bar", dish: "Clifton Burger & Mac & Cheese", url: "https://themanhattanprojectky.com", price: "$$" },
            { name: "Chik'n & Mi", location: "Clifton", cuisine: "Asian", dish: "Asian Fried Chicken", url: "https://chiknandmi.com", price: "$$" },
            { name: "Eatz Vietnamese Restaurant", location: "Clifton", cuisine: "Asian", dish: "Pho & Banh Mi", url: "https://www.facebook.com/EatzVietnameseRestaurant", price: "$$" },
            { name: "Morning Fork", location: "Clifton", cuisine: "Bakery & Breakfast", dish: "Short Rib Benedict", url: "https://morningforklouisville.com", price: "$$" },
            { name: "Time 4 Thai", location: "Clifton", cuisine: "Asian", dish: "Pad Thai & Crispy Garlic Shrimp", url: "https://time4thaiky.com", price: "$$" },
            { name: "Enso", location: "Clifton", cuisine: "Asian", dish: "Japanese Fusion", url: "https://enso-louisville.com", price: "$$" },
            { name: "CM Chicken of Louisville", location: "Clifton", cuisine: "Chicken", dish: "Korean Fried Chicken (Tikkudak)", url: "https://cmchickenoflouisville.com", price: "$$" },
            { name: "Volare Italian Ristorante", location: "Clifton", cuisine: "Italian", dish: "Sea Bass & Homemade Pastas", url: "https://volare-restaurant.com/dinner-menu/", price: "$$$" },
            { name: "Bourbon's Bistro", location: "Clifton", cuisine: "American (Upscale & Contemporary)", dish: "Bourbon Selection & Pork Chop", url: "https://bourbonsbistro.com-1", price: "$$$" },
            { name: "Crave Cafe", location: "Frankfort Ave / Crescent Hill", cuisine: "American (Casual & Burgers)", dish: "Granny Ruth's Chicken Salad", url: "https://cravecafeelouisville.com", price: "$" },
            { name: "Chicken King", location: "Downtown", cuisine: "Chicken", dish: "Spicy Chicken (Gold Sauce)", url: "https://www.facebook.com/ChickenKingLouisville", price: "$" },
            { name: "Safier Mediterranean Deli", location: "Downtown", cuisine: "International & Mediterranean", dish: "Shawarma & Hummus", url: "https://safierdeli.com", price: "$" },
            { name: "Abyssinia", location: "Downtown", cuisine: "International & Mediterranean", dish: "Doro Wot & Veggie Combo (Injera)", url: "https://abyssinialouisville.com", price: "$" },
            { name: "Bandido Taqueria", location: "Downtown", cuisine: "Mexican Latin & Caribbean", dish: "California Style Burritos", url: "https://bandidotaqueria.com", price: "$" },
            { name: "Old Spaghetti Factory", location: "Downtown", cuisine: "Italian", dish: "Mizithra Cheese & Browned Butter Pasta", url: "https://www.osf.com", price: "$$" },
            { name: "Doc Crow's ", location: "Downtown", cuisine: "Barbecue", dish: "Smokehouse BBQ & Oysters", url: "https://doccrows.com", price: "$$" },
            { name: "Troll Pub Under the Bridge", location: "Downtown", cuisine: "Pub & Bar", dish: "Beer Cheese & 'Louie the Troll' statue", url: "https://trollpub.com/louisville", price: "$$" },
            { name: "Merle's Whiskey Kitchen", location: "Downtown", cuisine: "Pub & Bar", dish: "Whiskey Selection & Tacos", url: "https://merleswhiskeykitchen.com", price: "$$" },
            { name: "Sidebar at Whiskey Row", location: "Downtown", cuisine: "American (Casual & Burgers)", dish: "Gourmet Burgers & Bourbon", url: "https://sidebarwhiskeyrow.com", price: "$$" },
            { name: "Porch Kitchen & Bar", location: "Downtown", cuisine: "Southern & Soul Food", dish: "Southern Comfort Food & Fried Chicken", url: "https://porchlouisville.com", price: "$$" },
            { name: "Brown Hotel Lobby Bar & Grill", location: "Downtown", cuisine: "American (Upscale & Contemporary)", dish: "The 'Original' Hot Brown", url: "https://www.brownhotel.com/dining/lobby-bar", price: "$$$" },
            { name: "Vincenzo's", location: "Downtown", cuisine: "Italian", dish: "Fine Italian Dining", url: "https://vincenzositalianrestaurant.com", price: "$$$" },
            { name: "Proof on Main", location: "Downtown", cuisine: "American (Upscale & Contemporary)", dish: "Bison Burger & Charred Octopus", url: "https://proofonmain.com", price: "$$$" },
            { name: "Jeff Ruby's Steakhouse", location: "Downtown", cuisine: "Steakhouse", dish: "The Collinsworth Steak & Sushi", url: "https://jeffruby.com/louisville", price: "$$$" },
            { name: "Brendon's Catch 23", location: "Downtown", cuisine: "Seafood", dish: "Seafood & Steaks", url: "https://bcatch23.com", price: "$$$" },
            { name: "Repeal Oak-Fired Steakhouse", location: "Downtown", cuisine: "Steakhouse", dish: "Oak-Fired Steaks", url: "https://repeallouisville.com", price: "$$$" },
            { name: "Swizzle Dinner & Drinks", location: "Downtown", cuisine: "Steakhouse", dish: "Revolving View & Pork Chops", url: "https://swizzlelouisville.com", price: "$$$" },
            { name: "Wild Swann", location: "Downtown", cuisine: "American (Upscale & Contemporary)", dish: "Steak Frites & Burger", url: "https://wildswann.com", price: "$$$" },
            { name: "Shreeji Indian Vegetarian Street Food", location: "East End", cuisine: "Asian", dish: "Pani Puri & Dabeli", url: "https://shreejiindianrestaurant.com", price: "$" },
            { name: "Take Thai", location: "East End", cuisine: "Asian", dish: "Pad Kee Mao & Curry", url: "https://takethaiky.com", price: "$" },
            { name: "Born 2 Bagel", location: "East End", cuisine: "Bakery & Breakfast", dish: "NY Style Bagels", url: "https://born2bagel.com", price: "$" },
            { name: "Tandoori Fusion", location: "East End", cuisine: "Asian", dish: "Indian Buffet", url: "https://tandoorifusionky.com", price: "$$" },
            { name: "Cask Southern Kitchen", location: "East End", cuisine: "Southern & Soul Food", dish: "Southern Food & Bourbon", url: "https://casksouthernkitchen.com", price: "$$" },
            { name: "Brasserie Provence", location: "East End", cuisine: "International & Mediterranean", dish: "French Onion Soup & Steak Frites", url: "https://brasserieprovence.com/dinner-menu/", price: "$$$" },
            { name: "Dairy Kastle", location: "Germantown / Schnitzelburg", cuisine: "Dessert & Sweets", dish: "Chili Dogs & Soft Serve", url: "https://www.facebook.com/DairyKastle", price: "$" },
            { name: "Hungry Pelican", location: "Fern Creek", cuisine: "Seafood", dish: "Fried Fish Platter", url: "https://hungrypelican.com", price: "$" },
            { name: "Bahn Thai", location: "Fern Creek", cuisine: "Asian", dish: "Pad Thai & Curries", url: "https://res-pick.com", price: "$$" },
            { name: "Blue Dog Bakery", location: "Frankfort Ave / Crescent Hill", cuisine: "Bakery & Breakfast", dish: "Artisan Bread & Pastries", url: "https://bluedogbakeryandcafe.com", price: "$" },
            { name: "Frankfort Avenue Beer Depot", location: "Frankfort Ave / Crescent Hill", cuisine: "Barbecue", dish: "BBQ & Patio", url: "https://frankfortavenuebeerdepot.com", price: "$" },
            { name: "El Mundo", location: "Frankfort Ave / Crescent Hill", cuisine: "Mexican Latin & Caribbean", dish: "Fish Tacos & Margaritas", url: "https://elmundo.org", price: "$$" },
            { name: "Osaka Japanese Restaurant", location: "Frankfort Ave / Crescent Hill", cuisine: "Asian", dish: "Sushi Rolls", url: "https://osakashushilouisville.com", price: "$$" },
            { name: "Con Huevos", location: "Frankfort Ave / Crescent Hill", cuisine: "Mexican Latin & Caribbean", dish: "Huevos Rancheros & Tres Leches", url: "https://conhuevos.com", price: "$$" },
            { name: "Red Hog", location: "Frankfort Ave / Crescent Hill", cuisine: "American (Casual & Burgers)", dish: "Butcher Cuts & Charcuterie", url: "https://redhogartisanmeat.com", price: "$$" },
            { name: "Porcini's", location: "Frankfort Ave / Crescent Hill", cuisine: "Italian", dish: "Lasagna & Fine Italian", url: "https://porcinilouisville.com/dinner-menu/", price: "$$$" },
            { name: "Check's Cafe", location: "Germantown / Schnitzelburg", cuisine: "American (Casual & Burgers)", dish: "Chili & Fish Sandwich", url: "https://checkscafelouisville.com", price: "$" },
            { name: "Nord's Bakery", location: "Germantown / Schnitzelburg", cuisine: "Bakery & Breakfast", dish: "Maple Bacon Donut", url: "https://www.facebook.com/NordsBakery/", price: "$" },
            { name: "Hauck's Corner", location: "Germantown / Schnitzelburg", cuisine: "American (Casual & Burgers)", dish: "Smashburgers", url: "https://hauckscorner.com", price: "$" },
            { name: "Jays Burgers", location: "Germantown / Schnitzelburg", cuisine: "American (Casual & Burgers)", dish: "Smashburgers", url: "https://www.eatjaysburgers.com/", price: "$" },
            { name: "Come Back Inn", location: "Germantown / Schnitzelburg", cuisine: "Italian", dish: "Italian-American Classics", url: "https://comebackinn.net", price: "$$" },
            { name: "Four Pegs", location: "Germantown / Schnitzelburg", cuisine: "Pub & Bar", dish: "Smoked Wings & Craft Beer", url: "https://fourpegs.com", price: "$$" },
            { name: "Hammerheads", location: "Germantown / Schnitzelburg", cuisine: "Pub & Bar", dish: "Duck Fat Fries & PBLT", url: "https://louisvillehammerheads.com", price: "$$" },
            { name: "The Post", location: "Germantown / Schnitzelburg", cuisine: "Pizza", dish: "NY Style Pizza by the slice", url: "https://thepostlouisville.com", price: "$$" },
            { name: "Monnik Beer Co.", location: "Germantown / Schnitzelburg", cuisine: "Pub & Bar", dish: "Craft Beer & Fries", url: "https://monnikbeer.com/food-menu/", price: "$$" },
            { name: "Sarino", location: "Germantown / Schnitzelburg", cuisine: "Italian", dish: "Neapolitan Pizza & Pasta", url: "https://sarinolouisville.com", price: "$$" },
            { name: "North of Bourbon", location: "Germantown / Schnitzelburg", cuisine: "American (Upscale & Contemporary)", dish: "Bourbon & Cajun/Creole", url: "https://northofbourbon.com", price: "$$" },
            { name: "Barret Bar", location: "Highlands", cuisine: "Pub & Bar", dish: "Brisket Quesadilla & Dry Rub Wings", url: "https://www.facebook.com/barretbar/", price: "$" },
            { name: "Twig and Leaf", location: "Highlands", cuisine: "American (Casual & Burgers)", dish: "Diner Breakfast", url: "https://twigandleaf.com/", price: "$" },
            { name: "Kern's Korner", location: "Highlands", cuisine: "Pub & Bar", dish: "The Burger (Wait List)", url: "https://www.facebook.com/Kernskorner", price: "$" },
            { name: "Bambi Bar", location: "Highlands", cuisine: "American (Casual & Burgers)", dish: "The Bambi Burger", url: "https://www.facebook.com/TheBambiBar", price: "$" },
            { name: "Shenanigans", location: "Highlands", cuisine: "Pub & Bar", dish: "Pub Burger & Guinness", url: "https://shenanigansirishgrille.com", price: "$" },
            { name: "Morris' Deli", location: "Highlands", cuisine: "American (Casual & Burgers)", dish: "Country Ham Sandwich", url: "https://www.morrisdeliky.com", price: "$" },
            { name: "La Bamba", location: "Highlands", cuisine: "Mexican Latin & Caribbean", dish: "Burritos 'As Big As Your Head'", url: "https://labambaburritos.com", price: "$" },
            { name: "Wiltshire Bakery", location: "Highlands", cuisine: "Bakery & Breakfast", dish: "Pastries & Sourdough", url: "https://wiltshirepantry.com/bakery/", price: "$" },
            { name: "Yummy Pollo", location: "Highlands", cuisine: "Chicken", dish: "Charcoal Rotisserie Chicken", url: "https://yummypollo.com", price: "$" },
            { name: "Banh Mi & Pho Lounge", location: "Highlands", cuisine: "Asian", dish: "Banh Mi & Pho", url: "https://www.facebook.com/BanhMiPhoLounge", price: "$" },
            { name: "Kebab House", location: "Highlands", cuisine: "International & Mediterranean", dish: "Gyros", url: "https://kebabhouseky.com/", price: "$" },
            { name: "Syrian Grill", location: "Highlands", cuisine: "International & Mediterranean", dish: "Chicken Shawarma", url: "https://www.facebook.com/SyrianGrillAbuAbdu", price: "$" },
            { name: "La Suerte", location: "Highlands", cuisine: "Mexican Latin & Caribbean", dish: "Latin Classics", url: "https://lasuertelouisville.com", price: "$" },
            { name: "M. Peppers", location: "Highlands", cuisine: "American (Casual & Burgers)", dish: "Au Poivre Burger", url: "https://mpeppers.com", price: "$" },
            { name: "80/20 at Kaelin's", location: "Highlands", cuisine: "American (Casual & Burgers)", dish: "Burgers & Milkshakes", url: "https://8020atkaelins.com", price: "$$" },
            { name: "Impellizzeri's Pizza", location: "Highlands", cuisine: "Pizza", dish: "Louisville-Style Pizza (Thick Crust)", url: "https://impellizzeris.com", price: "$$" },
            { name: "Uptown Cafe", location: "Highlands", cuisine: "American (Casual & Burgers)", dish: "Caesar Salad & Cakes", url: "https://uptownlouisville.com", price: "$$" },
            { name: "Ditto's", location: "Highlands", cuisine: "American (Casual & Burgers)", dish: "Thai Wings & The Grill", url: "https://dittosgrill.com", price: "$$" },
            { name: "Stevens & Stevens Deli", location: "Highlands", cuisine: "American (Casual & Burgers)", dish: "The Woody Allen (Pastrami)", url: "https://stevensdeli.com", price: "$$" },
            { name: "Ramsi's Cafe on the World", location: "Highlands", cuisine: "International & Mediterranean", dish: "Global Comfort Food (The World)", url: "https://ramsiscafe.com", price: "$$" },
            { name: "O'Shea's Irish Pub", location: "Highlands", cuisine: "Pub & Bar", dish: "Pub Food & Patio", url: "https://osheaslouisville.com", price: "$$" },
            { name: "Molly Malone's", location: "Highlands", cuisine: "Pub & Bar", dish: "Fish and Chips", url: "https://mollymalonesirishpub.com", price: "$$" },
            { name: "Kashmir Indian Restaurant", location: "Highlands", cuisine: "Asian", dish: "Butter Chicken", url: "https://kashmirlouisville.com", price: "$$" },
            { name: "Flanagan's Ale House", location: "Highlands", cuisine: "Pub & Bar", dish: "Pub Grub & Beer", url: "https://flanagansalehouse.com", price: "$$" },
            { name: "Sapporo Japanese Grill", location: "Highlands", cuisine: "Asian", dish: "Sushi & Teppanyaki", url: "https://sapporolouisville.com", price: "$$" },
            { name: "Queen of Sheba", location: "Highlands", cuisine: "International & Mediterranean", dish: "Ethiopian Platter (Injera)", url: "https://queenofshebalouisville.com", price: "$$" },
            { name: "Cafe Lou Lou", location: "Highlands", cuisine: "Pizza", dish: "Calzones & Cajun Pizza", url: "https://cafeloulou.com", price: "$$" },
            { name: "Dragon King's Daughter", location: "Highlands", cuisine: "Asian", dish: "Sushi Tacos", url: "https://dragonkingsdaughter.com", price: "$$" },
            { name: "Heart & Soy / Roots", location: "Highlands", cuisine: "Asian", dish: "Vegetarian Street Food & Tofu", url: "https://heartandsoy.net", price: "$$" },
            { name: "Holy Grale", location: "Highlands", cuisine: "Pub & Bar", dish: "Rare Beers & The Burger", url: "https://holygrale.com/food-menu/", price: "$$" },
            { name: "Superchefs", location: "Highlands", cuisine: "Bakery & Breakfast", dish: "Red Velvet Pancakes", url: "https://superchefs.com", price: "$$" },
            { name: "Bunz Burgerz", location: "Highlands", cuisine: "American (Casual & Burgers)", dish: "Baxter Ave Burger & Fries", url: "https://www.villagemarketfoodhall.com/bunz-burgerz", price: "$$" },
            { name: "Gralehaus", location: "Highlands", cuisine: "Bakery & Breakfast", dish: "Biscuits & Gravy / Coffee", url: "https://gralehaus.com", price: "$$" },
            { name: "The Eagle", location: "Highlands", cuisine: "Southern & Soul Food", dish: "Fried Chicken & Spoonbread", url: "https://eaglerestaurant.com", price: "$$" },
            { name: "Oskar's Slider Bar", location: "Highlands", cuisine: "American (Casual & Burgers)", dish: "Nordic Sliders", url: "https://oskarssliderbar.com", price: "$$" },
            { name: "Noche Mexican BBQ", location: "Highlands", cuisine: "Mexican Latin & Caribbean", dish: "Mexican BBQ & The Decor", url: "https://nocheMexicanbbq.com", price: "$$" },
            { name: "Good Belly", location: "Highlands", cuisine: "American (Casual & Burgers)", dish: "Pastrami & Corned Beef", url: "https://goodbellylouisville.com", price: "$$" },
            { name: "Palermo's", location: "Highlands", cuisine: "Italian", dish: "Tour of Italy & Pizza", url: "https://palermositalianrestaurant.com", price: "$$" },
            { name: "The Black Italian", location: "Highlands", cuisine: "Italian", dish: "Creamy Garlic Formaggio Pasta", url: "https://theblackitalian.com", price: "$$" },
            { name: "Wheated Pizza", location: "Highlands", cuisine: "Pizza", dish: "Sourdough Pizza (Ditmas Park)", url: "https://wheatedpizza.com/", price: "$$" },
            { name: "Jack Fry's", location: "Highlands", cuisine: "American (Upscale & Contemporary)", dish: "Shrimp & Grits & Lamb Chops", url: "https://jackfrys.com", price: "$$$" },
            { name: "Seviche A Latin Restaurant", location: "Highlands", cuisine: "Mexican Latin & Caribbean", dish: "Churrascos de Argentina & Ceviche", url: "https://sevicherestaurant.com", price: "$$$" },
            { name: "La Chasse", location: "Highlands", cuisine: "American (Upscale & Contemporary)", dish: "Wood-fired Grille & Game", url: "https://lachasselouisville.com/dinner-menu/", price: "$$$" },
            { name: "The Fat Lamb", location: "Highlands", cuisine: "American (Upscale & Contemporary)", dish: "Lamb Ribs", url: "https://fatlamblouisville.com", price: "$$$" },
            { name: "ROC", location: "Highlands", cuisine: "Italian", dish: "Fine Italian Dining", url: "https://rocrestaurant.com", price: "$$$" },
            { name: "Yi Sushi Omakase", location: "Highlands", cuisine: "Asian", dish: "Omakase & Wagyu Roll", url: "https://yisushiomakase.com", price: "$$$$" },
            { name: "Bristol Bar & Grille", location: "Highlands ", cuisine: "American (Casual & Burgers)", dish: "Green Chili Wontons", url: "https://bristolbarandgrille.com", price: "$$" },
            { name: "Wick's Pizza Parlor", location: "Highlands ", cuisine: "Pizza", dish: "The Big Wick (Thick Crust)", url: "https://wickspizza.com", price: "$$" },
            { name: "Havana Rumba", location: "Highlands ", cuisine: "Mexican Latin & Caribbean", dish: "Masas de Puerco & Mojitos", url: "https://havanarumba.com", price: "$$" },
            { name: "Highland Morning", location: "Highlands ", cuisine: "Bakery & Breakfast", dish: "Pancakes & Waffles", url: "https://highlandmorning.com", price: "$$" },
            { name: "Soupys", location: "Buechel / Hikes Point", cuisine: "American (Casual & Burgers)", dish: "Homemade Soups & Club Sandwich", url: "https://soupys.net", price: "$" },
            { name: "Grassa Gramma", location: "East End", cuisine: "Italian", dish: "Fresh Pasta & Elaborate Decor", url: "https://grassagramma.com/dinner-menu/", price: "$$$" },
            { name: "The Charcoal Restaurant", location: "East End", cuisine: "International & Mediterranean", dish: "Middle Eastern Chicken", url: "https://charcoalrestaurant.com", price: "$" },
            { name: "Yen Ching Chinese", location: "East End", cuisine: "Asian", dish: "General Tso's Chicken & Crab Rangoon", url: "https://yenchinglouisville.net", price: "$$" },
            { name: "Shalimar Indian Restaurant", location: "East End", cuisine: "Asian", dish: "Chicken Tikka Masala", url: "https://shalimarlouisville.com", price: "$$" },
            { name: "Payne Street Bakehouse", location: "Lexington Rd / Irish Hill", cuisine: "Bakery & Breakfast", dish: "Bagels (Smoked Salmon)", url: "https://paynestreetbakehouse.com", price: "$" },
            { name: "Spring Street Bar and Grill", location: "Lexington Rd / Irish Hill", cuisine: "Pub & Bar", dish: "Wings & Dive Bar Vibes", url: "https://springstreetbarandgrill.com", price: "$$" },
            { name: "Ramen House", location: "Lexington Rd / Irish Hill", cuisine: "Asian", dish: "Tonkotsu Ramen", url: "https://ramenhouselouisville.com", price: "$$" },
            { name: "Buds Tavern", location: "Jeffersontown", cuisine: "Pub & Bar", dish: "Fried Fish & Cold Beer", url: "https://budstavern.com", price: "$" },
            { name: "Passtime Fish House", location: "Jeffersontown", cuisine: "Seafood", dish: "Fried Fish & Frog Legs", url: "https://www.facebook.com/PasstimeFishHouse", price: "$$" },
            { name: "Mussel & Burger Bar", location: "Jeffersontown", cuisine: "American (Casual & Burgers)", dish: "CEO Burger & Mussels", url: "https://mussel-burger-bar.com", price: "$$" },
            { name: "Sichuan House", location: "Jeffersontown", cuisine: "Asian", dish: "Spicy Fish & Mapo Tofu", url: "https://sichuanhousekentucky.com", price: "$$" },
            { name: "Recbar", location: "Jeffersontown", cuisine: "Pub & Bar", dish: "Cereal Milkshakes & Tater Tots", url: "https://recbarlouisville.com", price: "$$" },
            { name: "Al Watan", location: "Buechel / Hikes Point", cuisine: "International & Mediterranean", dish: "Bakery & Middle Eastern", url: "https://alwatanbakery.com", price: "$" },
            { name: "Game", location: "Lexington Rd / Irish Hill", cuisine: "American (Casual & Burgers)", dish: "Exotic Meat Burgers (Elk/Kangaroo)", url: "https://wildgameburgers.com", price: "$$" },
            { name: "Le Moo", location: "Lexington Rd / Irish Hill", cuisine: "Steakhouse", dish: "Steak & Drunk Cut Fries", url: "https://lemoorestaurant.com/dinner-menu/", price: "$$$" },
            { name: "The Goose Eatery & Hangout", location: "East End", cuisine: "American (Casual & Burgers)", dish: "Hot Brown & Fried Green Tomatoes", url: "https://thegooselyndon.com", price: "$$" },
            { name: "Danny Mac's Pizza", location: "Frankfort Ave / Clifton", cuisine: "Pizza", dish: "Cracksticks & Pizza", url: "https://dannymacspizza.com", price: "$$" },
            { name: "Mellwood Tavern", location: "Frankfort Ave / Clifton", cuisine: "Pub & Bar", dish: "Fried Chicken (Tue/Thu)", url: "https://themellwoodtavern.com", price: "$$" },
            { name: "VinBun", location: "Middletown", cuisine: "Asian", dish: "Beef Pho & Banh Mi", url: "https://vinbun.com/", price: "$" },
            { name: "Highland Fish Market", location: "Middletown", cuisine: "Seafood", dish: "Fresh Fish & Crab Cakes", url: "https://highlandfish.com/", price: "$$" },
            { name: "Clay Oven", location: "Middletown", cuisine: "Asian", dish: "Butter Chicken & Naan", url: "https://clayovenlouisville.com", price: "$$" },
            { name: "Skyline", location: "Multiple Locations", cuisine: "American (Casual & Burgers)", dish: "Cincinnati Chili & Coneys", url: "https://skylinechili.com", price: "$" },
            { name: "Moby Dick", location: "Multiple Locations", cuisine: "Seafood", dish: "Fried Fish Sandwich", url: "https://mobydickrestaurants.com", price: "$" },
            { name: "Lee's Chicken", location: "Multiple Locations", cuisine: "Chicken", dish: "Spicy Fried Chicken", url: "https://leesfamousrecipe.com", price: "$" },
            { name: "Homemade Ice Cream and Pie Kitchen", location: "Multiple Locations", cuisine: "Dessert & Sweets", dish: "Dutch Apple Pie & Ice Cream", url: "https://piekitchen.com", price: "$" },
            { name: "Spinellis", location: "Multiple Locations", cuisine: "Pizza", dish: "Late Night NY Style Pizza", url: "https://spinellispizza.com", price: "$" },
            { name: "Carali's Rotisserie Chicken", location: "Multiple Locations", cuisine: "Chicken", dish: "Rotisserie Chicken", url: "https://caralischicken.com", price: "$" },
            { name: "I love Tacos", location: "Multiple Locations", cuisine: "Mexican Latin & Caribbean", dish: "Birria Tacos", url: "https://ilovetacoslouisville.com", price: "$" },
            { name: "Mark's Feed Store", location: "Multiple Locations", cuisine: "Barbecue", dish: "Burgoo & Honey Wings", url: "https://marksfeedstore.com", price: "$$" },
            { name: "Shiraz Grill", location: "Multiple Locations", cuisine: "International & Mediterranean", dish: "Kabobs & Basmati Rice", url: "https://shirazmediterranean.com", price: "$$" },
            { name: "Martins BBQ", location: "Multiple Locations", cuisine: "Barbecue", dish: "Whole Hog BBQ", url: "https://martinsbbqjoint.com", price: "$$" },
            { name: "Taco Luchador", location: "Multiple Locations", cuisine: "Mexican Latin & Caribbean", dish: "Tacos & Tortas", url: "https://el-taco-luchador.com", price: "$$" },
            { name: "Malone's", location: "Multiple Locations", cuisine: "Steakhouse", dish: "Prime Beef & Lexington Salad", url: "https://bluegrasshospitality.com/malones", price: "$$$" },
            { name: "Toast on Market", location: "NuLu", cuisine: "Bakery & Breakfast", dish: "Lemon Souffle Pancakes", url: "https://toastonmarket.com", price: "$$" },
            { name: "Mayan Cafe", location: "NuLu", cuisine: "Mexican Latin & Caribbean", dish: "Tok-sel Lima Beans & Cochinita Pibil", url: "https://themayancafe.com/dinner/", price: "$$" },
            { name: "Garage Bar", location: "NuLu", cuisine: "Pizza", dish: "Wood-fired Pizza & Country Ham", url: "https://garageonmarket.com", price: "$$" },
            { name: "Grind Burger Kitchen", location: "NuLu", cuisine: "American (Casual & Burgers)", dish: "B&B Burger & Veggie Burger", url: "https://grindburgerkitchen.com", price: "$$" },
            { name: "Feast BBQ", location: "NuLu", cuisine: "Barbecue", dish: "Brisket & Tater Tots", url: "https://feastbbq.com", price: "$$" },
            { name: "Royals Hot Chicken", location: "NuLu", cuisine: "Chicken", dish: "Nashville Hot Chicken", url: "https://royalshotchicken.com", price: "$$" },
            { name: "Emmy Squared", location: "NuLu", cuisine: "Pizza", dish: "Detroit Style Pizza", url: "https://emmysquaredpizza.com", price: "$$" },
            { name: "Bar Vetti", location: "NuLu", cuisine: "Italian", dish: "Pizza & Pasta", url: "https://barvetti.com", price: "$$" },
            { name: "Biscuit Belly", location: "NuLu", cuisine: "Bakery & Breakfast", dish: "The Rockwell (Fried Chicken Biscuit)", url: "https://biscuitbelly.com", price: "$$" },
            { name: "Lou Lou on Market", location: "NuLu", cuisine: "American (Upscale & Contemporary)", dish: "Cajun/Creole Fusion", url: "https://loulouonmarket.com", price: "$$" },
            { name: "Mashup Food Hall", location: "NuLu", cuisine: "American (Casual & Burgers)", dish: "Variety (Bagels Burgers Tacos)", url: "", price: "$$" },
            { name: "Pasta Garage", location: "NuLu", cuisine: "Italian", dish: "Fresh Pasta & Ragu Bolognese", url: "https://pastagaragenulu.com", price: "$$" },
            { name: "MeeshMeesh", location: "NuLu", cuisine: "International & Mediterranean", dish: "Levantine Cuisine", url: "https://meeshmeesh.com", price: "$$$" },
            { name: "Agave & Rye", location: "NuLu ", cuisine: "Mexican Latin & Caribbean", dish: "The 'Swipe Right' Taco", url: "https://agaveandrye.com", price: "$$" },
            { name: "Bar Genevieve", location: "NuLu (Hotel Genevieve)", cuisine: "American (Upscale & Contemporary)", dish: "Smashburger & Rooftop Cocktails", url: "https://bargenevieve.com", price: "$$$" },
            { name: "Cold Smoke Bagels", location: "NuLu (Mashup Food Hall)", cuisine: "Bakery & Breakfast", dish: "Lox Bagel & Egg Sandwich", url: "https://coldsmokebagels.com", price: "$$" },
            { name: "El Pastorcito", location: "South Louisville", cuisine: "Mexican Latin & Caribbean", dish: "Tacos Al Pastor & Birria", url: "https://orderelpastorcitotaqueria2.com", price: "$" },
            { name: "Old Louisville Tavern", location: "Old Louisville", cuisine: "Pub & Bar", dish: "Wings & Burgers", url: "https://oldlouisvilletavern.com", price: "$" },
            { name: "Granville Pub", location: "Old Louisville", cuisine: "Pub & Bar", dish: "Chili Cheese Fries & Pitchers", url: "https://www.facebook.com/GranvillePub", price: "$" },
            { name: "Dizzy Whizz", location: "Old Louisville", cuisine: "American (Casual & Burgers)", dish: "The Whizzburger", url: "https://dizzywhizz.com", price: "$" },
            { name: "Ollie's Trolley", location: "Old Louisville", cuisine: "American (Casual & Burgers)", dish: "The Ollie Burger & Fries", url: "https://www.facebook.com/OlliesTrolleyLouisville", price: "$" },
            { name: "Burger Boy", location: "Old Louisville", cuisine: "American (Casual & Burgers)", dish: "24/7 Diner Food", url: "https://www.burgerboyry.com", price: "$" },
            { name: "Pizza Donisi", location: "Old Louisville", cuisine: "Pizza", dish: "Late Night Pizza by the Slice", url: "https://pizzadonisi.com", price: "$" },
            { name: "Sam's Gyros", location: "Old Louisville", cuisine: "International & Mediterranean", dish: "Lamb Gyro Platter", url: "https://samsgyros.com", price: "$" },
            { name: "610 Magnolia", location: "Old Louisville", cuisine: "American (Upscale & Contemporary)", dish: "Chef's Tasting Menu", url: "https://610magnolia.com", price: "$$$" },
            { name: "Buck's Restaurant", location: "Old Louisville", cuisine: "American (Upscale & Contemporary)", dish: "White Flower Cake & Ambience", url: "https://www.bucksLou.com", price: "$$$" },
            { name: "Martini Italian Bistro", location: "East End", cuisine: "Italian", dish: "Lasagna & Martinis", url: "https://martinilouisville.com", price: "$$" },
            { name: "The Cafe ", location: "Highlands", cuisine: "American (Casual & Burgers)", dish: "The Hot Brown", url: "https://thecafe.com", price: "$$" },
            { name: "Maya Bagel Express", location: "Poplar Level", cuisine: "Bakery & Breakfast", dish: "Bagel Sandwiches", url: "https://mayabagelexpress.com", price: "$" },
            { name: "Kum's Cafe & Arirang", location: "Poplar Level", cuisine: "Asian", dish: "Dolsot Bibimbap & Galbi", url: "https://mybistro.online", price: "$$" },
            { name: "Open Caribbean Kitchen", location: "Poplar Level", cuisine: "Mexican Latin & Caribbean", dish: "Jerk Chicken & Oxtails", url: "https://opencaribbeankitchen.com", price: "$$" },
            { name: "Louie's Hot Chicken", location: "Poplar Level", cuisine: "Chicken", dish: "Nashville Hot Chicken & Brisket", url: "https://louieshotchickenandbbq.com", price: "$$" },
            { name: "Veronica's Mexican", location: "Poplar Level", cuisine: "Mexican Latin & Caribbean", dish: "Birria Platter & Quesabirria", url: "https://veronicasmexrest.com", price: "$$" },
            { name: "The Table", location: "Portland", cuisine: "American (Casual & Burgers)", dish: "Smoked Pork Sandwich & Pay-What-You-Can", url: "", price: "$" },
            { name: "Frank's Meat & Produce", location: "Preston Hwy", cuisine: "American (Casual & Burgers)", dish: "Ribeye Sandwich", url: "https://www.franksmeatandproduce.com/deli-menu", price: "$" },
            { name: "La Tropicana", location: "Preston Hwy", cuisine: "Mexican Latin & Caribbean", dish: "Authentic Tacos", url: "https://www.facebook.com/LaTropicanaLouisville", price: "$" },
            { name: "La Rosita", location: "Preston Hwy", cuisine: "Mexican Latin & Caribbean", dish: "Authentic Tacos & Tortas", url: "", price: "$" },
            { name: "Panchitos", location: "Preston Hwy", cuisine: "Dessert & Sweets", dish: "Ice Cream & Paletas", url: "https://panchitosicecream.com/", price: "$" },
            { name: "Tacolandia", location: "Preston Hwy", cuisine: "Mexican Latin & Caribbean", dish: "Tacos & Tortas", url: "https://tacolandiaworld.com", price: "$" },
            { name: "Mirage Mediterranean", location: "Preston Hwy", cuisine: "International & Mediterranean", dish: "Shawarma & Hummus", url: "https://miragemediterranean.com", price: "$$" },
            { name: "Koreana Restaurant III", location: "Preston Hwy", cuisine: "Asian", dish: "Galbi (Charcoal BBQ)", url: "https://koreana3bbq.com", price: "$$" },
            { name: "KingFish", location: "River Road", cuisine: "Seafood", dish: "Fried Fish & Hushpuppies", url: "https://kingfishrestaurants.com", price: "$$" },
            { name: "Captain's Quarters Riverside Grille", location: "River Road", cuisine: "Seafood", dish: "Fried Cod & Riverside Views", url: "https://cqriverside.com", price: "$$" },
            { name: "Cunningham's Creekside", location: "River Road", cuisine: "Seafood", dish: "Fried Fish Sandwich", url: "https://cunninghamscreekside.com", price: "$$" },
            { name: "River House Restaurant and Raw Bar", location: "River Road", cuisine: "Seafood", dish: "Seafood Tower & Patio Views", url: "https://riverhouselouisville.com", price: "$$$" },
            { name: "Franny's Seafood", location: "Germantown / Schnitzelburg", cuisine: "Seafood", dish: "Lobster Roll & Fish & Chips", url: "https://frannysseafood.com", price: "$$$" },
            { name: "Dairy Del", location: "Shelby Park", cuisine: "Dessert & Sweets", dish: "Soft Serve & Coneys", url: "https://dairydel.com", price: "$" },
            { name: "Shirley Mae's Cafe", location: "Shelby Park", cuisine: "Southern & Soul Food", dish: "Soul Food (Ribs & Wings)", url: "https://shirleymaescafe.com", price: "$" },
            { name: "Toastys Tavern", location: "Shelby Park", cuisine: "American (Casual & Burgers)", dish: "The Classic Burger", url: "https://toastystavern.com", price: "$" },
            { name: "Foko", location: "Shelby Park", cuisine: "Mexican Latin & Caribbean", dish: "Breakfast Burritos", url: "https://fokolouisville.com", price: "$" },
            { name: "Shahar Cafe", location: "Shelby Park", cuisine: "American (Casual & Burgers)", dish: "Vegan Burgers & Kickin Chicken", url: "https://shaharcafe.com", price: "$$" },
            { name: "Perso", location: "Shelby Park", cuisine: "Italian", dish: "Handmade Pasta", url: "https://persorestaurant.com", price: "$$" },
            { name: "Ott's Tavern", location: "South Louisville", cuisine: "Pub & Bar", dish: "Fish Sandwich & Bratwurst", url: "https://www.facebook.com/OttsTavern", price: "$" },
            { name: "Daddy Vic's Soul Food", location: "South Louisville", cuisine: "Southern & Soul Food", dish: "Fried Chicken & Boss Sauce", url: "https://daddyvicssoulfood.com", price: "$$" },
            { name: "Suburban Social Club Fish Fry", location: "South Louisville", cuisine: "Seafood", dish: "Green River Style Fish", url: "https://suburbanfishfry.com", price: "$" },
            { name: "Mike Linnig's", location: "South Louisville", cuisine: "Seafood", dish: "Fried Fish Sandwich & Onion Rings", url: "https://mikelinnigsrestaurant.com", price: "$" },
            { name: "Christi's Cafe", location: "South Louisville", cuisine: "American (Casual & Burgers)", dish: "The Big Dixie Burger & Breakfast", url: "https://www.christiscafe.com", price: "$" },
            { name: "Rubbies", location: "South Louisville", cuisine: "Barbecue", dish: "Smoked Wings & BBQ", url: "https://rubbiesbbq.com", price: "$" },
            { name: "Vietnam Kitchen", location: "South Louisville", cuisine: "Asian", dish: "K8 (Hu Tieu Satay Soup)", url: "https://www.facebook.com/VietnamKitchenLouisville", price: "$" },
            { name: "A Chau Restaurant", location: "South Louisville", cuisine: "Asian", dish: "Pho & Banh Mi", url: "https://chaus.top", price: "$" },
            { name: "DaLat's Cafe", location: "South Louisville", cuisine: "Asian", dish: "Banh Mi & Gelato", url: "https://www.facebook.com/DalatsCafe", price: "$" },
            { name: "La Chiquita Bakery", location: "South Louisville", cuisine: "Mexican Latin & Caribbean", dish: "Cuban Sandwich & Tres Leches", url: "https://www.facebook.com/LaChiquitaBakeryLouisville", price: "$" },
            { name: "La Torta Loca", location: "South Louisville", cuisine: "Mexican Latin & Caribbean", dish: "Tortas & Tacos", url: "https://www.facebook.com/LasTortasLocasLouisville", price: "$" },
            { name: "Kathmandu Kitchen", location: "South Louisville", cuisine: "Asian", dish: "Momos (Dumplings)", url: "https://kathmandukitchenky.com", price: "$" },
            { name: "Sam's Chicago Grill", location: "South Louisville", cuisine: "American (Casual & Burgers)", dish: "Chicago Italian Beef & Gyros", url: "https://samschicagogrill.com", price: "$" },
            { name: "Weekend Burger", location: "South Louisville", cuisine: "American (Casual & Burgers)", dish: "Smashburgers & Fried Cheesecake", url: "https://weekendburgers.com", price: "$" },
            { name: "Caribbean Cafe", location: "South Louisville", cuisine: "Mexican Latin & Caribbean", dish: "Oxtails & Jerk Chicken", url: "https://www.caribbeancafelouisville.com", price: "$" },
            { name: "Tumbleweed", location: "South Louisville", cuisine: "Mexican Latin & Caribbean", dish: "Chili Con Queso & Tex-Mex", url: "https://tumbleweedrestaurants.com", price: "$$" },
            { name: "Tuscany Italian", location: "South Louisville", cuisine: "Italian", dish: "Baked Pasta Trio & Meatball Sub", url: "https://tuscanyitalianky.net", price: "$$" },
            { name: "El Molcajete", location: "South Louisville", cuisine: "Mexican Latin & Caribbean", dish: "Molcajete Dish", url: "https://elmolcajetelouisville.com", price: "$$" },
            { name: "Anko Sushi", location: "South Louisville", cuisine: "Asian", dish: "Omakase & Crunch Munch Roll", url: "https://www.instagram.com/anko.sushi.louisville", price: "$$$" },
            { name: "Jamaican Jerk Center", location: "South Louisville", cuisine: "Mexican Latin & Caribbean", dish: "Jerk Chicken & Oxtails", url: "https://www.facebook.com/JamaicanJerkCenter", price: "$$" },
            { name: "Parkway Diner", location: "South Louisville", cuisine: "American (Casual & Burgers)", dish: "Pancakes & Potato Melt", url: "https://toasttab.com", price: "$" },
            { name: "Heitzman Bakery", location: "St. Matthews", cuisine: "Bakery & Breakfast", dish: "Donuts & Kuchens", url: "https://heitzmanbakery.com", price: "$" },
            { name: "Plehns Bakery", location: "St. Matthews", cuisine: "Bakery & Breakfast", dish: "Christmas Cookies & Kuchen", url: "https://plehns.com/bakery-menu/", price: "$" },
            { name: "W.W. Cousins", location: "St. Matthews", cuisine: "American (Casual & Burgers)", dish: "Build-Your-Own Burger Bar", url: "https://wwcousins.com", price: "$" },
            { name: "The Fishery", location: "St. Matthews", cuisine: "Seafood", dish: "Fried Fish Platter", url: "https://thefisheryky.com", price: "$" },
            { name: "Lonnie's Best Taste of Chicago", location: "St. Matthews", cuisine: "American (Casual & Burgers)", dish: "Chicago Dogs & Italian Beef", url: "https://www.lonniesbesttasteofchicago.com", price: "$" },
            { name: "Maira", location: "St. Matthews", cuisine: "International & Mediterranean", dish: "Gyro & Hummus", url: "https://mairamediteranean.com", price: "$" },
            { name: "Burger Girl Diner", location: "St. Matthews", cuisine: "American (Casual & Burgers)", dish: "24/7 Diner Food & Milkshakes", url: "https://burgergirl.com", price: "$" },
            { name: "Ricky B's Club Cafe", location: "St. Matthews", cuisine: "American (Casual & Burgers)", dish: "Club Sandwich & Wings", url: "https://www.facebook.com/RBClubCafe", price: "$" },
            { name: "Shawarma Shack", location: "St. Matthews", cuisine: "International & Mediterranean", dish: "Shawarma & Kunafa", url: "https://www.facebook.com/ShawarmaShackLou/", price: "$" },
            { name: "Bruegger's Bagels", location: "St. Matthews", cuisine: "Bakery & Breakfast", dish: "Bagels & Cream Cheese", url: "https://brueggers.com/", price: "$" },
            { name: "Oriental House", location: "St. Matthews", cuisine: "Asian", dish: "Authentic Dim Sum", url: "https://orientalhouselouisville.com", price: "$$" },
            { name: "Lotsa Pasta", location: "St. Matthews", cuisine: "Italian", dish: "Fresh Pasta & Deli Sandwiches", url: "https://lotsapasta.com", price: "$$" },
            { name: "Wild Eggs", location: "St. Matthews", cuisine: "Bakery & Breakfast", dish: "Kalamity Katie's Border Benedict", url: "https://wildeggs.com", price: "$$" },
            { name: "Nam Nam Cafe", location: "St. Matthews", cuisine: "Asian", dish: "Vietnamese Crepe (Banh Xeo) & Shaking Beef", url: "https://namnamcafe.com", price: "$$" },
            { name: "Coals Artisan Pizza", location: "St. Matthews", cuisine: "Pizza", dish: "Coal-Fired Pizza (The Waverly)", url: "https://coalsartisanpizza.com", price: "$$" },
            { name: "Momma's Mustard Pickles & BBQ", location: "St. Matthews", cuisine: "Barbecue", dish: "Smoked Wings & Fried Pickles", url: "https://mommasbbq.com", price: "$$" },
            { name: "Lori's Fish Market", location: "St. Matthews", cuisine: "Seafood", dish: "Smoked Salmon & Fish Fry", url: "https://lorisfish.com/", price: "$$" },
            { name: "Joella's Hot Chicken", location: "St. Matthews", cuisine: "Chicken", dish: "Hot Chicken & Spiked Honey", url: "https://joellas.com", price: "$$" },
            { name: "Silvio's Italian Restaurant", location: "St. Matthews", cuisine: "Italian", dish: "Lasagna", url: "https://silviositalianrestaurant.com", price: "$$" },
            { name: "Mojito in Havana", location: "St. Matthews", cuisine: "Mexican Latin & Caribbean", dish: "Cuban Sandwich & Mojitos", url: "https://mojitoinhavana.com", price: "$$" },
            { name: "Taco Choza", location: "St. Matthews", cuisine: "Mexican Latin & Caribbean", dish: "Birria Tacos & Margaritas", url: "https://tacochoza.com", price: "$$" },
            { name: "District 6", location: "St. Matthews", cuisine: "Asian", dish: "Vietnamese Gastropub", url: "https://district6louisville.com", price: "$$" },
            { name: "Bourbon and Burgers", location: "St. Matthews", cuisine: "American (Casual & Burgers)", dish: "Truffle Burger & Boozy Shakes", url: "https://bourbon-burgers.com", price: "$$" },
            { name: "Barry's Cheesesteaks", location: "South Louisville", cuisine: "American (Casual & Burgers)", dish: "Philly Cheesesteak", url: "https://www.barryscheesesteaks.com", price: "$$" },
            { name: "Indi's Chicken", location: "West End", cuisine: "Chicken", dish: "Spicy Fried Chicken & Wedges", url: "https://indischicken.com", price: "$" },
            { name: "Lucretia's Kitchen", location: "West End", cuisine: "Southern & Soul Food", dish: "Soul Food", url: "https://lucretiaskitchen.com", price: "$" },
            { name: "La Rosita Sol", location: "East End", cuisine: "Mexican Latin & Caribbean", dish: "Carne Asada Tacos & Horchata", url: "", price: "$" },
            { name: "Jade Palace", location: "East End", cuisine: "Asian", dish: "Authentic Dim Sum & Peking Duck", url: "https://jadepalacetogo.com", price: "$$" },
            { name: "Osteria Italian Seafood", location: "East End", cuisine: "Italian", dish: "Seafood Pasta", url: "https://osterialouisville.com", price: "$$$" },
        ]
    },
    "Late Night & 24/7": {
        description: "Where to go when the bars close or the insomnia kicks in.",
        type: "custom",
        items: [
            { header: "The 24/7 Legends" },
            { name: "Burger Boy Diner", note: "Old Louisville. The undisputed king of 24/7 diner food." },
            { name: "Burger Girl Diner", note: "Frankfort Ave. The sister diner to Burger Boy." },
            { name: "Waffle House", note: "Bardstown Rd & Crittenden Drive are late-night cultural experiences." },
            { header: "Late-Night Food (Open Past 1 AM)" },
            { name: "Spinelli's Pizzeria", note: "Multiple locations. NY style slices out of cars. Open until 5 AM." },
            { name: "Pizza Donisi", note: "Old Louisville. Tiny slice shop open until the Mag Bar crowd goes home." },
            { name: "La Bamba", note: "Highlands. 'Burritos as big as your head.' Open until 3 AM on weekends." },
            { name: "The Back Door", note: "Mid City Mall. Best late-night bar food in the city. Incredible wings." },
            { name: "Hilltop Tavern", note: "Clifton. Great for late-night meatloaf sandwiches or vegan BBQ." },
            { name: "Expo", note: "Downtown. Incredible late-night smashburgers hidden inside a neon-drenched dive." },
            { name: "Ramen House", note: "Highlands. Slurping tonkotsu broth at midnight." },
            { header: "4 AM Bars" },
            { name: "Mag Bar", note: "Old Louisville. Cheap beer, punk rock, malört, and a 4 AM last call." },
            { name: "The Back Door", note: "Highlands. Strongest, cheapest pours in the city until 4 AM." },
            { name: "The Outlook Inn", note: "Highlands. A classic, gritty late-night stop." },
            { name: "Hideaway Saloon", note: "Highlands. Video games, cheap drinks, upstairs view." },
            { name: "Seidenfaden's", note: "Germantown. Classic late-night neighborhood dive." }
        ]
    },
    "Museums & Galleries": {
        description: "The intersection of fine art, weird history, and local makers.",
        type: "custom",
        items: [
            { header: "The Heavy Hitters" },
            { name: "Speed Art Museum", note: "The oldest and largest art museum in Kentucky. Free on Sundays." },
            { name: "Frazier History Museum", note: "The official starting point of the Bourbon Trail." },
            { name: "Muhammad Ali Center", note: "A spectacular, multi-story interactive museum dedicated to the Greatest." },
            { name: "Kentucky Derby Museum", note: "Everything Churchill Downs, right next to the track." },
            { name: "Louisville Slugger Museum & Factory", note: "Look for the 120-foot baseball bat leaning against the building." },
            { name: "Roots 101 African American Museum", note: "Dedicated to telling the story of the African American journey from Africa to Kentucky." },
            { name: "KMAC Museum", note: "Contemporary art focusing on craft and material." },
            { name: "Kentucky Science Center", note: "Great for kids, but the 4-story theater is great for everyone." },
            { header: "Independent Galleries & Niche Museums" },
            { name: "21c Museum Hotel", note: "A free, 24/7 contemporary art museum disguised as a boutique hotel." },
            { name: "American Printing House for the Blind", note: "Fascinating tours showing how braille books and accessible tech are made." },
            { name: "Portland Museum", note: "A deep dive into the river heritage and history of the Portland neighborhood." },
            { name: "Thomas Edison House", note: "He lived in Louisville briefly; this shotgun house explores his time here." },
            { name: "Mellwood Art Center", note: "A massive former slaughterhouse turned into a maze of artist studios." },
            { name: "Revelry Boutique Gallery", note: "NuLu spot championing hyper-local artists." },
            { name: "Garner Narrative", note: "Intimate gallery in NuLu with a focus on contemporary, provocative pieces." },
            { name: "Howard Steamboat Museum", note: "Gorgeous Victorian mansion detailing riverboat history (Jeffersonville)." }
        ]
    },
    "Attractions & Outings": {
        description: "Things to do when you have guests in town, or just need to get out.",
        type: "custom",
        items: [
            { header: "Icons & Green Spaces" },
            { name: "The Belle of Louisville", note: "The oldest operating Mississippi-style steamboat in the world." },
            { name: "Louisville Zoo", note: "130 acres. The Glacier Run and Gorilla Forest are world-class." },
            { name: "Waterfront Botanical Gardens", note: "Built on top of a former landfill, now a stunning oasis overlooking the river." },
            { name: "Valhalla Golf Club", note: "Host of multiple PGA Championships. Very exclusive iconic sporting site." },
            { name: "Cave Hill Cemetery", note: "An incredibly beautiful Victorian garden cemetery. Visit Ali and Colonel Sanders." },
            { name: "The Big Four Bridge", note: "The pedestrian bridge connecting Louisville to Indiana. Best walked at sunset." },
            { header: "Entertainment & Oddities" },
            { name: "Louisville Mega Cavern", note: "A massive underground limestone quarry. Zipline or bike entirely underground." },
            { name: "Vernon Lanes", note: "Oldest bowling alley in KY. Recently restored, great food, historic lanes." },
            { name: "Recbar", note: "Massive warehouse packed with vintage arcade cabinets and pinball." },
            { name: "Fowling Warehouse", note: "Throwing footballs at bowling pins while drinking beer. It’s chaotic and fun." },
            { name: "Derby City Gaming", note: "Historical racing machines (essentially local slots)." }
        ]
    },
    "Thrift, Vintage & Digging": {
        description: "For sustainable shoppers, weirdos, and collectors.",
        type: "custom",
        items: [
            { header: "Curated Vintage & Boutiques" },
            { name: "The Nitty Gritty", note: "The absolute godfather of Louisville vintage clothing. Incredible curation." },
            { name: "Fat Rabbit Thrift & Vintage", note: "Cheap, chaotic, punk-rock thrift. Books, tapes, weird clothes." },
            { name: "Acorn Apparel", note: "Very trendy, curated 90s/Y2K and vintage streetwear." },
            { name: "Hey Tiger", note: "Eclectic mix of vintage and modern quirky clothes." },
            { name: "Barret Babes", note: "Inclusive, heavily curated vintage with a highly localized aesthetic." },
            { header: "Malls, Fleas & Digging" },
            { name: "Fleur de Flea Vintage Urban Market", note: "A massive, beautifully organized warehouse of vintage furniture and oddities." },
            { name: "Derby City Antique Mall", note: "30,000 sq ft of booths. You have to dig, but the prices are great." },
            { name: "Mellwood Antiques & Interiors", note: "Huge antique mall perfect for mid-century modern hunting." },
            { name: "Tickled Pink Memorabilia Mall", note: "Classic, dusty, packed-to-the-brim antique mall." },
            { name: "Peddler’s Malls", note: "Basically indoor yard sales. High trash-to-treasure ratio." }
        ]
    },
    "Active Louisville": {
        description: "How to burn off the bourbon and Hot Browns.",
        type: "custom",
        items: [
            { header: "Parks & Trails" },
            { name: "The Louisville Loop", note: "A paved path system that will eventually wrap 100 miles around the city." },
            { name: "The Parklands of Floyds Fork", note: "4,000 acres of meticulously designed new parks in the East End." },
            { name: "Jefferson Memorial Forest", note: "The largest municipal urban forest in the US. Real, elevation-heavy hiking." },
            { name: "Cherokee Park Loop", note: "The 2.4-mile scenic loop designed by Frederick Law Olmsted." },
            { header: "Adrenaline & Movement" },
            { name: "David Armstrong Extreme Park", note: "40,000 sq ft concrete skate park open 24/7. Famous for its massive 24-foot full pipe." },
            { name: "Climb NuLu", note: "Bouldering gym right in the middle of the NuLu neighborhood." },
            { name: "Rocksport", note: "Traditional top-rope and lead indoor climbing." },
            { name: "Louisville Hardcourt Bike Polo", note: "Playing polo on fixed-gear bikes in a concrete rink in Shelby Park." },
            { name: "Turners Circus", note: "Learn aerial silks, trapeze, and gymnastics at the historic Turners club." },
            { header: "Waterways" },
            { name: "Paddling Floyds Fork", note: "Rent a kayak from Blue Moon Canoe & Kayak and float down the scenic creek." },
            { name: "Harrods Creek", note: "A slow, beautiful creek feeding into the Ohio River. Rent a kayak from Nachand." }
        ]
    },
    "Clubs & Activities": {
        description: "How to meet people in this town—from mainstream kickball to obscure street games.",
        type: "custom",
        items: [
            { header: "Active & Sports Leagues" },
            { name: "LXC Sports", note: "The massive mainstream option. Kickball, dodgeball, softball, and flag football." },
            { name: "World Championship Dainty", note: "A Schnitzelburg tradition since 1971. A game for those 45+. Involves a stick, a 'dainty', and the street." },
            { name: "Louisville Hardcourt Bike Polo", note: "Shelby Park. Fast, aggressive, and incredibly niche." },
            { name: "Derby City Run Club", note: "Meets at local breweries for runs. Very social; people usually stay for a pint after." },
            { name: "SAK Softball", note: "Competitive and recreational softball leagues at various city parks." },
            { name: "Louisville Darts", note: "Competitive and casual dart leagues around town." },
            { name: "Louisville APA Poolplayers Association", note: "The local chapter for amateur pool leagues, playing out of various dive bars and halls." },
            { name: "Derby City Roller Girls", note: "Flat-track roller derby. A great community for those looking for intensity and camaraderie." },
            { name: "Fowling Warehouse", note: "Football + Bowling. A bizarre hybrid sport that shouldn't work, but does." },
            { header: "The DIY & Maker Scene" },
            { name: "LVL1 Hackerspace", note: "A 24/7 community lab for geeks, engineers, and artists. If you want to build a flamethrower or a robot, go here." },
            { name: "Falls City Community Bikeworks", note: "A DIY shop where you learn to fix your own bike using their tools and knowledge." },
            { name: "Louisville Tool Library", note: "Borrow a power drill or a ladder like you borrow a book." },
            { name: "Payne Street Pottery", note: "Classes and open studio time. Pottery is a very 'zen' way to meet consistent faces." },
            { header: "Games & Nerd Culture" },
            { name: "Louisville Board Gamers", note: "A huge, welcoming group that meets at various libraries and game shops (Heroes, Through the Decades)." },
            { name: "Zanzabar Pinball League", note: "Competitive flipping at one of the best arcades in the region." },
            { name: "Bridge Clubs", note: "The Louisville Bridge Association (LBA) on Bardstown Rd is the hub for players." },
            { header: "Nature & Outdoors" },
            { name: "Louisville Hiking Club", note: "A very active group that organizes group hikes in Jefferson Memorial Forest and the Gorge." },
            { name: "Louisville Grotto", note: "The local chapter of the National Speleological Society. For people who like crawling through caves." },
            { name: "Beckham Bird Club", note: "For birdwatchers. They do field trips to Cave Hill and the Falls of the Ohio." },
            { name: "Louisville Grows", note: "Community gardening and tree planting. Great for meeting people who care about the environment." },
            { header: "Movement & Arts" },
            { name: "Derby City Swing", note: "West Coast Swing dancing. They do weekly lessons and social dances." },
            { name: "Louisville Country Dancers", note: "Contra Dancing at various church halls. Incredibly welcoming to beginners." },
            { name: "Turners Circus", note: "Aerial silks, trapeze, and gymnastics. A very tight-knit 'circus family' vibe." },
            { name: "Silent Reading Party", note: "For people who want to go to a bar and read a book in total silence with others." },
            { name: "Fearless Comedy / Improv", note: "Intro to improv classes. The fastest way to break the ice with strangers." },
            { header: "The Strange & Obscure" },
            { name: "Waverly Hills Sanatorium", note: "The massive, decaying epicenter of Louisville ghost lore. Overnight stays for the brave." },
            { name: "Kentucky Bigfoot Research Organization", note: "Yes, they are active. Yes, they take it seriously. Keep your eyes on the woods." },
            { name: "American Printing House for the Blind", note: "Factory tours of a unique world-class facility hidden in Clifton." },
            { header: "Civic & Professional" },
            { name: "YPAL (Young Professionals Association)", note: "The standard for networking if you are 20-40 and looking for social crossovers." },
            { name: "Rotary Club of Louisville", note: "One of the largest in the world. High-level networking and city service." },
            { name: "Neighborhood Associations", note: "Search for your specific 'hood (Clifton, Germantown, etc). Meet your actual neighbors." },
            { name: "KY Harm Reduction Coalition", note: "Community health, overdose prevention, and harm reduction resources.", url: "https://louisvilleky.gov/government/health-wellness/harm-reduction" }
        ]
    },
    // The rest of the original lists (Oldest Restaurants, Parks, Grocery, etc) remain here.
    "Oldest Restaurants": {
        description: "The survivors.",
        type: "ranked",
        items: [
            { name: "Wagner's Pharmacy", year: "1922", },
            { name: "English Grill at the Brown Hotel", year: "1923", },
            { name: "Mike Linnig's", year: "1925", },
            { name: "Jack Fry's", year: "1933", note: "Closed from 1972 – 1981" },
            { name: "Old Louisville Tavern", year: "1933" },
            { name: "Checks Café", year: "1935" },
            { name: "Granville Pub", year: "1939" },
            { name: "Dizzy Whizz", year: "1947" },
            { name: "KingFish", year: "1948" },
            { name: "Dairy Del", year: "1951" },
            { name: "Pat's Steakhouse", year: "1958" },
            { name: "Twig and Leaf", year: "1962" },
            { name: "Ott's Tavern", year: "1963" },
            { name: "Oriental House", year: "1964" },
            { name: "Ollie's Trolley", year: "1973" },
            { name: "Moby Dick", year: "1975" },
            { name: "The Old Spaghetti Factory", year: "1975" },
            { name: "Dairy Kastle", year: "1976" },
            { name: "The Bristol Bar & Grille", year: "1977" },
            { name: "Bearno's Pizza", year: "1977" },
            { name: "Kern's Korner", year: "1978" },
            { name: "Hungry Pelican", year: "1978" },
            { name: "Frank's Meat and Produce", year: "1979" },
            { name: "Impellizzeri's", year: "1979" },
            { name: "Burger Boy Diner", year: "1980" },
            { name: "The Fishery", year: "1980" },
            { name: "Lee's Korean", year: "1980" },
            { name: "Porcini", year: "1980" },
        ],
        honorableMentions: [
            { name: "The Old Talbott Tavern", year: "1779", note: "Bardstown" },
            { name: "Cunningham’s Creekside", year: "1870", note: "Closings and Location Changes." },
            { name: "Mellwood Tavern", year: "1885", note: "Longest Continually Running Tavern" },
            { name: "Schimpff Confectionery", year: "1891", note: "Jeffersonville" },
            { name: "Heitzman Bakery", year: "1891", },
            { name: "Suburban Social Club Fish Fry", year: "1919", note: "Saturday's Only" },
            { name: "Muth's Candies", year: "1920", },
            { name: "Plehn's Bakery", year: "1922", }
        ]
    },
    "Oldest Landmarks": {
        description: "History in stone and brick.",
        type: "ranked",
        items: [
            { year: "1786", name: "First Public Cemetery", note: "Jefferson St between 11th and 12th" },
            { year: "1792", name: "Locust Grove", note: "Final home of George Rogers Clark" },
            { year: "1812", name: "Squire Earick House", note: "Oldest wood-frame house in Louisville - Portland" },
            { year: "1816", name: "Farmington", note: "Design by Thomas Jefferson" },
            { year: "1824", name: "Christ Church Cathedral", note: "Oldest church in Louisville" },
            { year: "1830", name: "Louisville and Portland Canal" },
            { year: "1837", name: "Bank of Louisville", note: "Now the Actors Theatre lobby" },
            { year: "1838", name: "Louisville Metro Hall" },
            { year: "1848", name: "Cave Hill Cemetery" },
            { year: "1848", name: "Eastern Cemetery", note: "Most over-buried cemetery in the US abandoned in 1989." },
            { year: "1852", name: "Cathedral of the Assumption", note: "3rd oldest Catholic Cathedral in US" },
            { year: "1858", name: "American Printing House for the Blind" },
            { year: "1860", name: "Louisville Water Tower", note: "World's oldest ornamental water tower" },
            { year: "1860", name: "Old Louisville Historic District", note: "Largest collection of Victorian homes in US" },
            { year: "1873", name: "Louisville City Hall" },
            { year: "1875", name: "Churchill Downs", note: "Twin Spires added in 1895" },
            { year: "1877", name: "Crescent Hill Reservoir" },
            { year: "1879", name: "Simmons College of Kentucky", note: "HBCU founded by former slaves" },
            { year: "1880", name: "St. James Court" },
            { year: "1884", name: "Louisville Slugger Museum & Factory" },
            { year: "1891", name: "Olmsted Parks Founded" },
            { year: "1891", name: "Union Station" },
            { year: "1895", name: "Conrad-Caldwell House" },
            { year: "1895", name: "Big Four Bridge" },
            { year: "1905", name: "Filson Historical Society" },
            { year: "1905", name: "The Seelbach" },
            { year: "1908", name: "Louisville Free Public Library", note: "Main Branch" },
            { year: "1910", name: "Vernon Lanes", note: "Oldest bowling alley in Kentucky" },
            { year: "1914", name: "Belle of Louisville", note: "Oldest operating Mississippi-style steamboat" },
            { year: "1923", name: "The Brown Hotel", note: "Birthplace of the 'Hot Brown' (1926)" },
            { year: "1926", name: "Waverly Hills Sanatorium" },
            { year: "1928", name: "The Pendennis Clubhouse" },
            { year: "1928", name: "The Palace Theatre" },
            { year: "1929", name: "Louisville Memorial Auditorium" }
        ]
    },
    "Parks": {
        description: "Green Spaces.",
        type: "custom", 
        items: [
            { header: "Olmsted Parks" },
            { name: "Algonquin Park" },
            { name: "Baxter Square" },
            { name: "Bingham Park" },
            { name: "Boone Square" },
            { name: "Central Park" },
            { name: "Cherokee Park" },
            { name: "Chickasaw Park" },
            { name: "Elliott Park" },
            { name: "Iroquois Park" },
            { name: "Seneca Park" },
            { name: "Shawnee Park" },
            { name: "Shelby Park" },
            { name: "Stansbury Park" },
            { name: "Tyler Park" },
            { name: "Victory Park" },
            { name: "Wayside Park" },
            { name: "Willow Park" },
            { header: "Other Notable Parks" },
            { name: "Jefferson Memorial Forest" },
            { name: "Parklands of Floyds Fork" },
            { name: "Tom Sawyer State Park" },
            { name: "Waterfront & Botanical Gardens" },
            { name: "Waverly Park" }
        ]
    },
    "Grocery": {
        description: "Local Provisions.",
        type: "alpha",
        items: [
            { name: "Lotsa Pasta" },
            { name: "Paul's Fruit Market" },
            { name: "Rainbow Blossom" },
            { name: "Frank's Meat & Produce" },
            { name: "Garden Gate Fruit Market" },
            { name: "Supermercado Guanajuato" },
            { name: "Foods World" },
            { name: "Five Star Halal Grocery" },
            { name: "Reardon's Fruit Market" },
            { name: "Kingsley Meats & Catering" },
            { name: "Red Hog" },
            { name: "Lori's Fish Market" },
            { name: "Highland Fish Market" },
            { name: "Viet Hoa Food Market" },
            { name: "Patel Brothers" },
        ]
    },
    "Music Venues": {
        description: "Live and Loud.",
        type: "alpha",
        items: [
            { name: "Mag Bar" },
            { name: "Camp Spaceman" },
            { name: "Whirling Tiger" },
            { name: "Zanzabar" },
            { name: "Portal" },
            { name: "Camp Social Club" },
            { name: "Headliners" },
            { name: "Mercury Ballroom" },
            { name: "Paristown Hall" }
        ]
    },
    "Theatre / The Stage": {
        description: "Live Performances.",
        type: "alpha",
        items: [
            { name: "Actors Theatre of Louisville" },
            { name: "The Louisville Ballet" },
            { name: "KY Opera" },
            { name: "The Brown Theatre" },
            { name: "Louisville Palace Theatre" },
            { name: "KY Center for the Performing Arts" },
            { name: "Bunbury Theatre" },
            { name: "Stage One" },
            { name: "Dinner Detective Murder Mystery" },
            { name: "Derby Dinner Playhouse" },
            { name: "Belknap Playhouse" },
            { name: "Thrust Theatre" },
            { name: "UL College of Art’s and Sciences" },
            { name: "Highview Arts Center" },
            { name: "Louisville Comedy Club" },
            { name: "Comedy Caravan" },
            { name: "Planet of the Tapes" }
        ]
    },
    "Golf & Disc Golf": {
        description: "Fore!",
        type: "custom",
        items: [
            { header: "Ball Golf Courses" },
            { name: "Charlie Vettiner Park" },
            { name: "Cherokee Park" },
            { name: "Crescent Hill Park" },
            { name: "Iroquois Park" },
            { name: "Long Run Park" },
            { name: "Seneca Park" },
            { name: "Shawnee Park" },
            { name: "Sun Valley Park" },
            { name: "Waverly Park" },
            { header: "Disc Golf Courses" },
            { name: "Bullitt County Disc Golf Course" },
            { name: "Charlie Vettiner Park" },
            { name: "Highview Park Disc Golf Course" },
            { name: "Iroquois Park" },
            { name: "Lapping Park", note: "Clarksville" },
            { name: "Louisville Champions Park" },
            { name: "Ryan's Course at Red Orchard Park", note: "Shelbyville" },
            { name: "Wendell Moore Disc Golf Course" }
        ]
    },
    "Notable Annual Events": {
        description: "Mark your calendar.",
        type: "events",
        items: [
            { name: "St. Patrick's Day Parade", month: "March", monthIndex: 3 },
            { name: "Nulu Bock Beer Fest", month: "March", monthIndex: 3 },
            { name: "Frankfort Ave Easter Parade", month: "April", monthIndex: 4 },
            { name: "Thunder Over Louisville", month: "April", monthIndex: 4 },
            { name: "Cherokee Triangle Art Fair", month: "April", monthIndex: 4 },
            { name: "Great Balloon Race", month: "April", monthIndex: 4 },
            { name: "Pegasus Parade", month: "May", monthIndex: 5 },
            { name: "Steamboat Race", month: "May", monthIndex: 5 },
            { name: "KY Shakespeare Festival", month: "May-Aug", monthIndex: 5 },
            { name: "Kentuckiana Pride Festival", month: "June", monthIndex: 6 },
            { name: "Butchertown Art Fair", month: "June", monthIndex: 6 },
            { name: "Waterfront Independence Festival", month: "July", monthIndex: 7 },
            { name: "World Championship Dainty Contest", month: "July", monthIndex: 7 },
            { name: "KY State Fair", month: "August", monthIndex: 8 },
            { name: "St. Joes Picnic", month: "August", monthIndex: 8 },
            { name: "World Fest", month: "Sept", monthIndex: 9 },
            { name: "Louisville Pride Festival", month: "Sept", monthIndex: 9 },
            { name: "Butchertown Oktoberfest", month: "Sept", monthIndex: 9 },
            { name: "St. James Court Art Show", month: "October", monthIndex: 10 },
            { name: "Jack O'Lantern Spectacular", month: "October", monthIndex: 10 },
            { name: "Louisville International Film Festival", month: "October", monthIndex: 10 },
            { name: "Highland Renaissance Festival", month: "Oct", monthIndex: 10 },
            { name: "Light Up Louisville", month: "Nov/Dec", monthIndex: 11 },
            { name: "Fete de Noel", month: "December", monthIndex: 12 },
            { name: "Old Louisville Holiday Home Tour", month: "December", monthIndex: 12 },
            { name: "Actors Theatre of Louisville", month: "Season", monthIndex: 13 },
            { name: "WHAS Crusade for Children", month: "June", monthIndex: 6 },
            { name: "Bourbon & Beyond", month: "Sept", monthIndex: 9 },
            { name: "Louder Than Life", month: "Sept", monthIndex: 9 },
            { name: "Garvin Gate Blues Festival", month: "October", monthIndex: 10 },
        ]
    },
    "Dive Bars": {
        description: "Cheap drinks, dim lights.",
        type: "alpha",
        items: [
            { name: "Air Devils Inn" },
            { name: "Bambi Bar" },
            { name: "Barret Bar" },
            { name: "Bud’s Tavern" },
            { name: "Canary Club" },
            { name: "Dive Bar" },
            { name: "Frankfort Ave Beer Depot" },
            { name: "Hideaway Saloon" },
            { name: "High Horse" },
            { name: "Kaiju" },
            { name: "Kern's Korner" },
            { name: "Left Field Lounge" },
            { name: "Mag Bar" },
            { name: "Mellwood Tavern" },
            { name: "Nachbar" },
            { name: "Seidenfadens" },
            { name: "Shenanigans" },
            { name: "Spring Street Bar" },
            { name: "Stooges" },
            { name: "The Mellwood Tavern" },
            { name: "The Merryweather" },
            { name: "The Outlook Inn" },
            { name: "The Pearl" },
            { name: "Third Street Dive" },
            { name: "Whirling Tiger" }
        ]
    },
    "Breweries": {
        description: "Local suds.",
        type: "alpha",
        items: [
            { name: "3rd Turn Brewing" },
            { name: "Against The Grain Brewery" },
            { name: "Akasha Brewing Company" },
            { name: "Atrium Brewing" },
            { name: "Awry" },
            { name: "Bluegrass Brewing" },
            { name: "Butchertown Brewing" },
            { name: "Gallant Fox" },
            { name: "Gravely Brewing" },
            { name: "Holsopple Brewing" },
            { name: "Hop Atomica" },
            { name: "Mile Wide Beer Co" },
            { name: "Monnik Beer Company" },
            { name: "Noble Funk" },
            { name: "Old Louisville Brewery" },
            { name: "TEN20" },
            { name: "Trellis Brewing" },
            { name: "West Sixth Nulu" }
        ]
    },
    "Coffee": {
        description: "Caffeine fixes.",
        type: "custom",
        items: [
            { header: "Roasters and Cafe" },
            { name: "Red Hot Roasters" },
            { name: "Safai Coffee" },
            { name: "Sunergos Coffee" },
            { name: "Good Folks Coffee" },
            { name: "Fante’s Coffee" },
            { name: "Phalcha Coffee" },
            { name: "Ithmah Coffee Roasters" },
            { name: "Bean Roastery and Cafe" },
            { name: "Brew & Sip" },
            { name: "Hinterhof" },
            { header: "Cafe" },
            { name: "Barista Parlor" },
            { name: "Bayt Al mocha" },
            { name: "Blackbeard" },
            { name: "Blak Koffee" },
            { name: "Butchertown Bakery" },
            { name: "Day’s Coffee" },                
            { name: "Full Stop" },
            { name: "Goldies" },
            { name: "Good Folks Coffee" },
            { name: "Haraz" },
            { name: "Haymarket River Rd" },
            { name: "Heine Bros" },
            { name: "La Pana Bakery" },
            { name: "Louisville Joe Coffee" },
            { name: "Nook and Nowhere" },
            { name: "North Lime Coffee & Donuts" },
            { name: "Ntaba" },                
            { name: "Please & Thank You" },
            { name: "Pregame" },
            { name: "Quills Coffee" },
            { name: "The Well" },
            { name: "Whirling Tiger Coffee" },
            { name: "Witches Brew" }		
        ]
    },
    "Sports": {
        description: "The Teams.",
        type: "custom",
        items: [
            { name: "Bellarmine Knights", note: "Freedom Hall" },
            { name: "Louisville Bats", note: "Louisville Slugger Field" },
            { name: "Louisville Cardinals Basketball", note: "KFC Yum! Center" },
            { name: "Louisville Cardinals Football", note: "L&N Stadium" },
            { name: "Louisville Cardinals Hockey", note: "Iceland Sports Complex" },
            { name: "Louisville City FC", note: "Lynn Family Stadium" },
            { name: "Racing Louisville FC", note: "Lynn Family Stadium" }
        ]
    },
    "Education": {
        description: "Higher Learning.",
        type: "custom",
        items: [
            { header: "Universities & Colleges" },
            { name: "Bellarmine University", url: "https://www.bellarmine.edu/" },
            { name: "Galen College of Nursing", url: "https://galencollege.edu/" },
            { name: "Indiana University Southeast", url: "https://www.ius.edu/" },
            { name: "Jefferson Community & Technical College", url: "https://jefferson.kctcs.edu/" },
            { name: "Purdue Polytechnic", note: "New Albany", url: "https://polytechnic.purdue.edu/locations/new-albany" },
            { name: "Spalding University", url: "https://spalding.edu/" },
            { name: "Sullivan University", url: "https://www.sullivan.edu/" },
            { name: "University of Louisville", url: "https://louisville.edu/" },
            { header: "Seminaries & Religious Colleges" },
            { name: "Boyce College", url: "https://boycecollege.com/" },
            { name: "Indiana Wesleyan University" },
            { name: "Louisville Presbyterian Theological Seminary" },
            { name: "McKendree University" },
            { name: "Simmons College of Kentucky", url: "https://simmonscollegeky.edu/" },
            { name: "The Southern Baptist Theological Seminary" }
        ]
    },
    "Libraries": {
        description: "Books & Tools.",
        type: "custom",
        items: [
            { name: "Louisville Tool Library" },
            { name: "LFPL Main Branch" },
            { name: "Bon Air" },
            { name: "Crescent Hill" },
            { name: "Fairdale" },
            { name: "Highlands-Shelby Park" },
            { name: "Iroquois" },
            { name: "Jeffersontown" },
            { name: "Middletown" },
            { name: "Newburg" },
            { name: "Northeast Regional" },
            { name: "Portland" },
            { name: "Shawnee" },
            { name: "Shively" },
            { name: "South Central Regional" },
            { name: "Southwest Regional" },
            { name: "St. Matthews" },
            { name: "Western" }
        ]
    },
    "Local News": {
        description: "Read all about it.",
        type: "alpha",
        items: [
            { name: "Courier Journal", url: "https://www.courier-journal.com/" },
            { name: "LEO Weekly", url: "https://www.leoweekly.com/" },
            { name: "WAVE3", url: "https://www.wave3.com/" },
            { name: "WDRB", url: "https://www.wdrb.com/" },
            { name: "WHAS11", url: "https://www.whas11.com/" },
            { name: "WLKY", url: "https://www.wlky.com/" }
        ]
    },
    "Local Business": {
        description: "Non-Dining Oddities & Shops.",
        type: "alpha",
        items: [
            { name: "Barret Babes" },
            { name: "Better Days Records" },
            { name: "Caufield’s Novelty" },
            { name: "Doo Wop Shop" },
            { name: "Electric Ladyland" },
            { name: "Fat Rabbit Thrift" },
            { name: "Flea de Fleur" },
            { name: "Guestroom Records" },
            { name: "Home Skateshop" },
            { name: "Idlewild Butterfly Farm" },
            { name: "Keith's Hardware" },
            { name: "Leatherhead" },
            { name: "Logan Street Market" },
            { name: "Louisville Antique Market" },
            { name: "Louisville Nature Center" },
            { name: "LVL1 Hackerspace" },
            { name: "Mom’s Music" },
            { name: "Natural Mystic" },
            { name: "Oscars Hardware" },
            { name: "Planet of the Tapes" },
            { name: "Preston Arts Center" },
            { name: "Surface Noise" },
            { name: "Swag's Sport Shoes" },
            { name: "The Great Escape" },
            { name: "Tickled Pink Memorabilia Mall" },
            { name: "Waverly Hills Sanatorium" },
            { name: "Work the Metal" }
        ]
    },
    "Bike Shops": {
        description: "Rubber side down.",
        type: "custom",
        items: [
            { name: "Falls City Community BikeWorks!", note: "Volunteer Based Community Shop" },
            { name: "CycleSmiths" },
            { name: "Grit Cycling" },
            { name: "Middletown Cycling" },
            { name: "N+1 Bikes" },
            { name: "On your Left" },
            { name: "Parkside Bikes" },
            { name: "Shifty Business Cycleworks" },
            { name: "Vic’s Classic Bikes" }
        ]
    },
    "Bookstores": {
        description: "Read local.",
        type: "alpha",
        items: [
            { name: "A Novel Romance" },
            { name: "Butcher Cabin Books" },
            { name: "Carmichael’s Bookstore" },
            { name: "Foxing Bookstore" },
            { name: "Nook and Nowhere" },
            { name: "Set & Setting" }
        ]
    },
    "Cinema & Drive-Ins": {
        description: "Silver Screens",
        type: "alpha",
        items: [
            { name: "Sauerbeck Family Drive-In", note: "La Grange" },
            { name: "Georgetown Drive-In", note: "Georgetown, IN" },
            { name: "Speed Cinema", note: "Indie/Art films at Speed Museum" },
            { name: "Preston Hwy Drive-In", note: "Since 1945, Cash only." },
            { name: "Xscape Theatres", },
            { name: "Tinseltown", },
            { name: "Cinemark", note: "Mall St. Matthews" },
            { name: "Cinemark", note: "Preston Crossings" },
            { name: "AMC Stonybrook", }
        ]
    }
};